<?php
set_time_limit(10);
require_once '../src/whatsprot.class.php';
//Change to your time zone
date_default_timezone_set('Europe/Madrid');


// phone number, deviceIdentity, and name.
$options = getopt("d::", array("debug::"));
//$debug = (array_key_exists("debug", $options) || array_key_exists("d", $options)) ? true : false;

########## DO NOT COMMIT THIS FILE WITH YOUR CREDENTIALS ###########
///////////////////////CONFIGURATION///////////////////////
//////////////////////////////////////////////////////////
$username = "**your phone number**";                      // Telephone number including the country code without '+' or '00'.
$password = "**server generated whatsapp password**";     // A server generated Password you received from WhatsApp. This can NOT be manually created
$identity = "**unique ID generated by WhatsApp client**"; // Obtained during registration with this API or using MissVenom (https://github.com/shirioko/MissVenom) to sniff from your phone.
$nickname = "**your nickname**";                          // This is the username (or nickname) displayed by WhatsApp clients.
$target = "**contact's phone number**";                   // Destination telephone number including the country code without '+' or '00'.
$debug = false;                                           // Set this to true, to see debug mode.
///////////////////////////////////////////////////////////


$username = "380676188068";                      // Telephone number including the country code without '+' or '00'.
$password = "ADBWpJ7j91cyNLTyApY97UfNWLA=";     // A server generated Password you received from WhatsApp. This can NOT be manually created
$identity = "%17%9fkd4ll%c5%c3ti%df%7cd%8b%a9%a9%fd%1du"; // Obtained during registration with this API or using MissVenom (https://github.com/shirioko/MissVenom) to sniff from your phone.
$nickname = "";                          // This is the username (or nickname) displayed by WhatsApp clients.
$target = "380999760371";                   // Destination telephone number including the country code without '+' or '00'.
$debug = true;           


function fgets_u($pStdn)
{
    $pArr = array($pStdn);

    if (false === ($num_changed_streams = stream_select($pArr, $write = NULL, $except = NULL, 0))) {
        print("\$ 001 Socket Error : UNABLE TO WATCH STDIN.\n");

        return FALSE;
    } elseif ($num_changed_streams > 0) {
        return trim(fgets($pStdn, 1024));
    }
    return null;
}

//This function only needed to show how eventmanager works.
function onGetProfilePicture($from, $target, $type, $data)
{
    if ($type == "preview") {
        $filename = "preview_" . $target . ".jpg";
    } else {
        $filename = $target . ".jpg";
    }
    $filename = WhatsProt::PICTURES_FOLDER."/" . $filename;
    $fp = @fopen($filename, "w");
    if ($fp) {
        fwrite($fp, $data);
        fclose($fp);
    }

    echo "- Profile picture saved in /".WhatsProt::PICTURES_FOLDER."\n";
}

function onPresenceReceived($username, $from, $type)
{
	$dFrom = str_replace(array("@s.whatsapp.net","@g.us"), "", $from);
		if($type == "available")
    		echo "<$dFrom is online>\n\n";
    	else
    		echo "<$dFrom is offline>\n\n";
}

echo "[] Logging in as '$nickname' ($username)\n";

function onMessageReceivedClient($mynumber, $from, $id, $type, $time) {
        echo "Message from $mynumber:\n$from\n\n";
}



//Create the whatsapp object and setup a connection.
$w = new WhatsProt($username, $identity, $nickname, $debug);
$w->connect();

// Now loginWithPassword function sends Nickname and (Available) Presence
$w->loginWithPassword($password);

//echo "[*] Connected to WhatsApp\n\n";

//Retrieve large profile picture. Output is in /src/php/pictures/ (you need to bind a function
//to the event onProfilePicture so the script knows what to do.
//$w->eventManager()->bind("onGetProfilePicture", "onGetProfilePicture");
//$w->sendGetProfilePicture($target, true);

//Print when the user goes online/offline (you need to bind a function to the event onPressence
//so the script knows what to do)
//$w->eventManager()->bind("onPresence", "onPresenceReceived");

$w->eventManager()->bind("onMessageReceivedClient", "onMessageReceivedClient");


echo $w->getJID($username);

//update your profile picture
//$w->sendSetProfilePicture("demo/venom.jpg");

//send picture
//$w->sendMessageImage($target, "demo/x3.jpg");

//send video
//$w->sendMessageVideo($target, 'http://techslides.com/demos/sample-videos/small.mp4');

//send Audio
//$w->sendMessageAudio($target, 'http://www.kozco.com/tech/piano2.wav');

//send Location
//$w->sendMessageLocation($target, '4.948568', '52.352957');



// Implemented out queue messages and auto msgid
$w->sendMessage($target, "380973924271");
//$w->sendMessage($target, "Sent from WhatsApi at " . date('H:i'));

//while($w->pollMessage());

/**
 * You can create a ProcessNode class (or whatever name you want) that has a process($node) function
 * and pass it through setNewMessageBind, that way everytime the class receives a text message it will run
 * the process function to it.
 */
//$pn = new ProcessNode($w, $target);
//$w->setNewMessageBind($pn);

//echo "\n\nYou can also write and send messages to $target (interactive conversation)\n\n> ";


